server:
  port: 20020

alibaba:
  acm:
    dataId: belinkBonus
    endpoint: jmenv.tbsite.net
    namespace: b9f3d027-ead3-4bf5-8a70-9e2195373559
    accessKey: 443e2d2a13004a2fa16c06883591680a
    secretKey: o+/U1KgoxBS/eKpILd8zZf+BbLM=
    group: belink

spring:
  application:
    name: bonus-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://101.251.195.186:3306/belink_wallet?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: smartlife
    password: belink!@#
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

mq:
  server:
    address: 114.67.126.146:9092,114.67.126.146:9192
    topic:
      transactionNotify: TIP_BELINK1
      dataStatistical: TIP_BELINK2

belink:
  settlement:
    channels: MobileBank;InternetBank;

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

dubbo:
  scan:
    base-packages: com.belink.chain.bonus.gateway.dubbo
  protocol:
    name: dubbo
#    host: 101.251.195.187
    port: 12345
  registry:
    address: zookeeper://114.67.126.146:2181,zookeeper://114.67.126.146:2191


