spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
info:
  app:
    name: guoliuqiangdemp
    version: v1.0.0

#指定全局的配置文件
mybatis-plus:
  config-location: classpath:mybatis-config.xml
