spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://101.251.195.186:3306/test?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: smartlife
    password: belink!@#
    driverClassName: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
info:
  app:
    name: guoliuqiangdemp
    version: v1.0.0
