version: '3'    #版本号

networks:
  mynet:

services:   #服务，下一级均为服务名
  zookeeper0:
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888
    ports:
    - 2181:2181
    - 2888:2888
    networks:
    - mynet

  zookeeper1:
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
    - ZOO_MY_ID=2
    - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888
    ports:
    - 2191:2181
    - 2898:2888
    networks:
    - mynet

  kafka0:
    image: hyperledger/fabric-kafka
    restart: always
    environment:
    - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
    - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
    - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
    - KAFKA_BROKER_ID=0
    - KAFKA_MIN_INSYNC_REPLICAS=2
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181
    ports:
    - 9092:9092
    depends_on:
    - zookeeper0
    - zookeeper1
    networks:
    - mynet

  kafka1:
    image: hyperledger/fabric-kafka
    restart: always
    environment:
    - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
    - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
    - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
    - KAFKA_BROKER_ID=1
    - KAFKA_DEFAULT_REPLICATION_FACTOR=3
    - KAFKA_MIN_INSYNC_REPLICAS=2
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181
    ports:
    - 9192:9092
    depends_on:
    - zookeeper0
    - zookeeper1
    networks:
    - mynet

  redis:
    image: redis
    container_name: redis01
    ports:
    - 6379:6379
    volumes:
    - /data/redis/redis.conf:/etc/redis/redis.conf
    - /data/redis/data:/data
    networks:
    - mynet
    command: redis-server /etc/redis/redis.conf --appendonly yes

  bonus:
    image: 37677b95d130
    container_name: bonus                                                      #生成容器名
    tty: true
    ports:                                                                   #配置端口
    - "10021:10021"       #映射端口:软件端口
    - "10020:10020"
    - "20020:20020"
    depends_on:
    - redis
    - zookeeper0
    - zookeeper1
    - kafka0
    - kafka1
    volumes:
    - /data/belinkwallet:/data/belinkwallet
    networks:           #网络名（仅为一个标记，用来保证所有容器运行与同一网络下，保证容器间的互相通信的可行性）
    - mynet

  manager:
    image: 37677b95d130
    container_name: manager
    tty: true
    ports:
    - "28090:28090"       #映射端口:软件端口
    - "18089:18089"
    - "8089:8089"
    volumes:
    - /data/belinkwallet:/data/belinkwallet
    networks:
    - mynet


